version: "3"

services:
  webapp:
    build: ./webapp
    command: npm start
    volumes:
     - ./webapp:/var/www/
    ports:
      - "5000:8080"
    networks:
      - front-tier
      - back-tier

  monitor:
    build: ./monitor
    command: npm start
    volumes:
      - ./monitor:/var/www/
    ports:
      - "5001:8080"
    networks:
      - front-tier
      - back-tier

  # worker:
  #   build:
  #     context: ./worker
  #   depends_on:
  #     - "redis"
  #   networks:
  #     - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  # sqldb:
  #   image: mariadb
  #   container_name: sqldb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: docker
  #     MYSQL_USER: testdbuser
  #     MYSQL_PASSWORD: testdbpassword
  #     MYSQL_DATABASE: teststatdb
  #   volumes:
  #     - ./data/maria:/var/lib/mysql
  #   ports:
  #     - 8306:3306
  #   networks:
  #     - back-tier

  sqldb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: testdbuser
      MYSQL_PASSWORD: testdbpassword
      MYSQL_DATABASE: teststatdb
    networks:
      - back-tier
    volumes:
      - ./data/maria:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

networks:
  front-tier:
  back-tier: