version: "3"
services:

  hello:
    image: game.lieray.de/dexta/hello-docker:0.6
    environment:
      - NODE_hello=dexta
    ports:
      - "8000:8080"
    networks:
      - helloFrontend
    deploy:
      mode: replicated
      replicas: 8
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure


networks:
  helloFrontend: