version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontendNetwork
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    environment:
      - VIRTUAL_HOST=portainer.dockerlocal
      - VIRTUAL_PORT=9000
    networks:
      - frontendNetwork


networks:
  frontendNetwork:
  backendNetwork: